### ISSUE TITLE
ElevenLabs <> Maximiliano

### ISSUE THREAD

**Issue by PiotrDabkowski** [maxilevi/leastsquares.io#10]
Sorry for spam via github issue (I could not find your email!).
I am a co-founder of ElevenLabs - an audio research lab, I like your projects and would love to speak with you if you have some time!

**Comment by maxilevi** [comment]
Hey, thanks for reaching out :)

Would love to speak! Let's coordinate via email, my personal is maxilevi77 at gmail dot com

**Comment by PiotrDabkowski** [comment]
Resolved :)
